services:
  db:
    image: postgres:16-alpine
    container_name: bonmiel-postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
      - bonmiel-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bonmiel_admin -d bonmiel"]
      interval: 5s
      timeout: 5s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: bonmiel-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bonmiel.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"

volumes:
  bonmiel-data:
